<?php

/**
 * Implements hook_init.
 */
function csc_column_init() {
  $path = drupal_get_path('module', 'csc_column');
  drupal_add_js($path . '/js/csc_column.js');
  drupal_add_css($path . '/css/csc_column.css');
}

function csc_column_login(){
  //Load login block from user module
  $block = block_load('user', 'login');
  $render_array = _block_get_renderable_array(_block_render_blocks(array($block)));
  $output = render($render_array);
  
  echo $output;
}

function csc_column_search(){
$output .='
<form accept-charset="UTF-8" method="post" action="'. url('csc_do_find') .'"><div><div class="container-inline">
<input type="hidden" name="q" value="'. url('search/site') .'">
      <h2 class="element-invisible">Search form</h2>
    <div class="form-item form-type-textfield form-item-search-block-form">
  <label for="field-key" class="element-invisible">Search </label>
 <input type="text" class="form-text" maxlength="128" size="15" value="" name="key" id="field-key" title="Enter the terms you wish to search for.">
</div>
<div id="edit-actions" class="form-actions form-wrapper"><input type="submit" class="form-submit" value="Search"></div>
</div>
</div></form>';

echo $output;
}

function csc_column_find(){
  $key = urlencode($_POST['key']);
  $url = url('search/site/' . $key);
  drupal_goto('search/site/' . $key);
}

function csc_column_search_original(){
  //Load block from search module
  $block = block_load('search', 'form');
  $render_array = _block_get_renderable_array(_block_render_blocks(array($block)));
  $output = render($render_array);
  
  echo $output;
}

function csc_column_contact(){
  echo "Contact information";
}

function csc_column_explore(){
  echo "Eploring CSC";
}

/**
 * Implements hook menu
 */
function csc_column_menu(){
  $items['csc_column/login'] = array(
    'page callback' => 'csc_column_login',
    'access arguments' => array('access content'),
  );

  $items['csc_column/search'] = array(
    'page callback' => 'csc_column_search',
    'access arguments' => array('access content'),
  );
  
  $items['csc_column/contact'] = array(
    'page callback' => 'csc_column_contact',
    'access arguments' => array('access content'),
  );
  
  $items['csc_column/explore'] = array(
    'page callback' => 'csc_column_explore',
    'access arguments' => array('access content'),
  );
  
  $items['csc_do_find'] = array(
    'page callback' => 'csc_column_find',
    'access arguments' => array('access content'),
  );  
  
  return $items;
} 